### ISSUE TITLE
More functionality for Machine Config Card

### ISSUE THREAD

**Issue by WhitePhant0m** [Swedz/Extended-Industrialization#12]
Feature 1:
Allow machine config card to copy and paste items in to machines(Redstone Control Module, Upgrades, Hull)
Would take the items from players inventory, and if the player doesn't have enough items, just paste the settings.

Feature 2:
Auto apply configs to compatible machine if the card is held in off-hand while placing machines.

**Comment by Swedz** [comment]
Both features are added in 1.6.0+1.21
