### ISSUE TITLE
Can't lock slots with recipe from EMI

### ISSUE THREAD

**Issue by WhitePhant0m** [Swedz/Extended-Industrialization#13]
![image](https://github.com/user-attachments/assets/d300be2f-8ac8-45d3-b387-6285f272e344)
Tried with Bending Machine and Alloy Smelter

EMI: 1.1.11
MI: 2.2.16-beta
ExI: 1.5.3
Tesseract: 1.2.6

Pack: [Craftoria 0.7.0](https://www.curseforge.com/minecraft/modpacks/craftoria/files/5611431)

**Comment by Swedz** [comment]
This is a much more complicated issue than I first thought. I'll talk to tech about this and get back to this within a few updates for Tesseract

**Comment by Swedz** [comment]
Forgot to close this issue, but it was fixed in EI 1.7.0 and Tesseract 1.3.0
