### ISSUE TITLE
Extended Industrialization seems to crash the game upon entering world creation screen

### ISSUE THREAD

**Issue by Hach1221** [Swedz/Extended-Industrialization#14]
[crash-2024-08-12_15.38.21-client.txt](https://github.com/user-attachments/files/16580465/crash-2024-08-12_15.38.21-client.txt)

**Comment by Hach1221** [comment]
And yes, this happens with 1.5.4 update installed as well

**Comment by Swedz** [comment]
Can you confirm that this happens on MI 2.2.16-beta? It appears 2.2.17 breaks EI

**Comment by Hach1221** [comment]
@Swedz Yes, the latest version of MI paired with EI is what is causing this. Downgraded to 2.2.16 and there are no issues.

**Comment by Swedz** [comment]
Fixed in EI 1.5.5 and Tesseract 1.2.8
