### ISSUE TITLE
Chained chainers with fast input causes horrendous performance

### ISSUE THREAD

**Issue by WhitePhant0m** [Swedz/Extended-Industrialization#15]
https://spark.lucko.me/ieZdfigT10
![{EA900D49-2499-4C44-8735-076DA7136425}](https://github.com/user-attachments/assets/cf6eb310-130f-4184-aa43-0e97ed3786c2)

Images of the setup used:
![image](https://github.com/user-attachments/assets/95732e29-e650-434d-8207-da5ac22bc001)
![{3776FDA1-7ED1-4AA1-9687-6DAEA950314C}](https://github.com/user-attachments/assets/00a2feda-5a9b-4edf-9d36-3d7b827e5ad0)
![{5A31FD9D-AF25-44EF-9D68-8FDB3B348E2F}](https://github.com/user-attachments/assets/e26181cd-5621-4b09-9656-ab3d8f9b0fe5)
![{43930559-A459-4500-99C6-7EA08CE040D7}](https://github.com/user-attachments/assets/b4d40dad-6492-44ca-8b2e-c0e8fbc93af5)
pack being [Craftoria v0.8.0](https://legacy.curseforge.com/minecraft/modpacks/craftoria/files/5626126)

**Comment by WhitePhant0m** [comment]
Seems to happen when machines it triest to insert into are full

**Comment by Swedz** [comment]
Should be fixed in 1.7.2, let me know if the issue persists :)
