### ISSUE TITLE
Auto extract for Machine Chainer

### ISSUE THREAD

**Issue by Swedz** [Swedz/Extended-Industrialization#26]

**Comment by Nensec** [comment]
You could make this only auto extract from the blocks it is chained to that also have this setting enabled.

Inversely, auto input could be a thing as well.

**Comment by Swedz** [comment]
Doing that would create a lot of confusion as it's not an intuitive function. If you need some machines to auto extract from the chainer and others to not, it would be best to use multiple chainers.

As for auto insert, you can achieve that functionality using configurable chests.
