### ISSUE TITLE
Does Not Support Accessories and the Curios Compat Layer

### ISSUE THREAD

**Issue by Xaeive** [Swedz/Extended-Industrialization#44]
When Accessories and Curios Compat Layer for Accessories are both installed and enabled, this mod then requires Curios 9.0.10+ when the Curios Compat is only 9.0.5

I saw you have dependencies for both Curios and Accessories, I wonder if you have Curios set as a higher priority than Accessories? Causing it to use Curios instead of Accessories, but since the Compat Layer is a lower level than what you require, it does not work.

![Screenshot 2024-09-17 111813](https://github.com/user-attachments/assets/ded450ff-b861-4169-a2ca-89773f9cb963)

EDIT: When i disabled the Compat Layer, the mod loaded, but then all my Curios mods stopped working.

**Comment by Swedz** [comment]
Why does the curios compat layer use the mod id `curios`... that's frustrating. ~~Yes it has to do with priorities.~~ This is an easy fix.

**Comment by Swedz** [comment]
I think the only issue here is the version requirement. The accessories compat is set to be higher priority than curios.
