### ISSUE TITLE
Mystical Agriculture crops not functioning with Extended Industrialization Farmer

### ISSUE THREAD

**Issue by yepbeeble** [Swedz/Extended-Industrialization#54]
Using the Electric Farmer to plant Mystical Agriculture crops functions, but when the plants are mature they are not harvested and put in to the output hatch of the multiblock structure. Fertilizer does not work either, probably because they are not bonemealable by normal means.
![image](https://github.com/user-attachments/assets/f76c4283-0aa2-4ad3-9294-1183b0fd159e)
Image Above shows that the crops plant properly

Using /gamerule randomTickSpeed 50 to speed up the crop growth (under normal circumstances, this functions properly) the crops remain mature and do not get harvested by the farmer

Screenshot showing the unharvested crops
![image](https://github.com/user-attachments/assets/cf4a896a-83cb-4817-8a51-26c7bdf67a3f)
Screenshot showing the valid multiblock structure
![image](https://github.com/user-attachments/assets/79bd741c-140a-4226-85ff-4b4f2a0e77a6)

**Comment by Swedz** [comment]
Added in #64
