### ISSUE TITLE
[Suggestion] More Large Multiblocks

### ISSUE THREAD

**Issue by Desempregago** [Swedz/Extended-Industrialization#57]
# Feasible
• Compressor
**(higher plate/curved plate/ring throughput when compared to a single block compressor)**

• Cutting Machine
**(could use two bronze fluid input hatches or a single steel hatch for the fluid inputs)**

# Kinda Complicated
• Mixer
**(would need at least 1 input and output hatch, steel tier only)**

**Comment by Swedz** [comment]
At least for now, I don't think there's much precedent to add these multiblocks. Eventually I'll add KJS support for batch crafting machines.

**Comment by yepbeeble** [comment]
an earlygame alternative to the processing array is just a machine chainer with copies of the machines you want to mass produce. Other than that, at mid or late game, just use the processing array.
