### ISSUE TITLE
Multi Processing Array with Electric Quarry consumes multiple drills at a time.

### ISSUE THREAD

**Issue by kalutro** [Swedz/Extended-Industrialization#59]
As the title states, it seems the roll for consuming the drill is global and not for each individual drill. This means when the roll passes, multiple drills are consumed. If using 64 Quarries you could go through an entire stack of drills with a single unlucky roll.

Is this intended?

**Comment by Swedz** [comment]
The multi processing array is not from Extended Industrialization, and yes, that is likely intentional.
