### ISSUE TITLE
Steam Chainsaw does not consume water

### ISSUE THREAD

**Issue by James103** [Swedz/Extended-Industrialization#62]
As of Modern Industrialization 2.2.25 and Extended Industrialization 1.9.4-beta-1.21.1 for Minecraft 1.21.1 and NeoForge 21.1.77, the Steam Chainsaw does not consume water, only fuel. This is unlike the Steam Drill from base MI, which does consume both fuel and water.

To reproduce, get a Steam Drill and a Steam Chainsaw, fill them both with fuel and water, and use both tools once each. Observe the fuel and water levels as the current fuel item is burning.

**Comment by Swedz** [comment]
If you have a water bucket in your inventory (or any other water container), it will pull from that. Same goes for MI's steam drill. Can you confirm this is not what's causing this?

**Comment by James103** [comment]
I tested hitting an armor stand using both a Steam Drill and a Steam Chainsaw, without anything else in my inventory. Results:
* Steam Drill uses a piece of fuel and a corresponding amount of water, resulting in its water level going down.
* Steam Chainsaw uses a piece of fuel, but its water level does not go down.

**Comment by Swedz** [comment]
You're right. Thank you. I will fix this for the next release
