### ISSUE TITLE
Steam/Electric Farmer does not detect tree growth from Oh The Biomes We've Gone

### ISSUE THREAD

**Issue by James103** [Swedz/Extended-Industrialization#63]
The Steam and Electric Farmer does not detect trees which grow from the Oh The Biomes We've Gone mod, even though vanilla trees and Integrated Dynamics menril trees are detected.

I reported this issue here: https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/171 saying it may be because the `TreeGrowthEvent` this mod is listening for isn't being fired. The author of that mod wrote that the event would have to be fired and linked a screenshot of some code highlighting `BlockGrowFeatureEvent`.

However, trees from that mod, when they grow, still aren't cut down by this mod's farmer multiblocks.

**Comment by Swedz** [comment]
I made a comment on the other issue on my findings. Not sure if there is a good way to add this support

**Comment by Swedz** [comment]
I could make a conditional mixin that would inject at the end of `TreeFromStructureNBTFeature#place` from OTYG and capture the blocks placed. Might be worth doing

**Comment by Swedz** [comment]
Added in Swedz/tesseract-neoforge#49
