### ISSUE TITLE
Server crash due to incorrect itemstack states stored in a Machine Config Card

### ISSUE THREAD

**Issue by James103** [Swedz/Extended-Industrialization#70]
I copied a machine configuration from an assembler using a Machine Config Card and was pasting it to other assemblers when the server crashed with this error while saving my inventory:
```
java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air; Value must be within range [1;99]: 0; Item must not be minecraft:air
```
The item which failed to save was the aforementioned Machine Config Card (`[1 extended_industrialization:machine_config_card]`), with the following components:
```
{
	extended_industrialization:machine_config=>MachineConfig[machineBlock=Block{modern_industrialization:assembler}, slots=MachineConfigSlots[slots=[ItemSlot[index=0, capacity=64, lock=modern_industrialization:stainless_steel_plate], ItemSlot[index=1, capacity=64, lock=modern_industrialization:stainless_steel_curved_plate], ItemSlot[index=2, capacity=64, lock=modern_industrialization:stainless_steel_rod], ItemSlot[index=3, capacity=64, lock=modern_industrialization:stainless_steel_gear], ItemSlot[index=4, capacity=64, lock=minecraft:air], ItemSlot[index=5, capacity=64, lock=minecraft:air], ItemSlot[index=6, capacity=64, lock=minecraft:air], ItemSlot[index=7, capacity=64, lock=minecraft:air], ItemSlot[index=8, capacity=64, lock=minecraft:air], ItemSlot[index=9, capacity=64, lock=modern_industrialization:stainless_steel_drill_head], ItemSlot[index=10, capacity=64, lock=minecraft:air], ItemSlot[index=11, capacity=64, lock=minecraft:air], FluidSlot[index=0, lock=aztech.modern_industrialization.fluid.MIFluid@7c415c29], FluidSlot[index=1, lock=net.minecraft.world.level.material.EmptyFluid@dbdbdcd]], itemSlotCount=12, fluidSlotCount=2], orientation=MachineConfigOrientation[facingDirection=south, hasOutput=true, outputDirection=down, extractItems=true, extractFluids=false], panel=MachineConfigPanel[slotItems={UPGRADES=0 minecraft:air, CASINGS=0 minecraft:air}]]
	minecraft:max_stack_size=>1
	minecraft:lore=>ItemLore[lines=[], styledLines=[]]
	minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}
	minecraft:repair_cost=>0
	minecraft:attribute_modifiers=>ItemAttributeModifiers[modifiers=[], showInTooltip=true]
	minecraft:rarity=>COMMON
}
```
As a result, my inventory was reverted to the state it was from the last autosave.

EDIT: The machine config card had stored "0 air" for both the upgrade slot and the casing slot, which causes the above error when the inventory containing the card is saved.

Modpack: Craftoria 1.9.0
Extended Industrialization `1.9.4-beta-1.21.1`
Modern Industrialization `2.2.25`
MI Tweaks `1.5.3-beta-1.21.1`
Tesseract API `1.5.4-beta-1.21.1`
Minecraft 1.21.1
NeoForge 21.1.79

**Comment by Swedz** [comment]
Can you please send the full stacktrace? This was an issue a while back but I was pretty confident it was fixed. Odd to see it pop up again

**Comment by James103** [comment]
Attached is the crash report and zipped `latest.log` for the crash.
[crash-2024-12-10_21.52.05-server.txt](https://github.com/user-attachments/files/18089482/crash-2024-12-10_21.52.05-server.txt)
[latest.zip](https://github.com/user-attachments/files/18089486/latest.zip)

**Comment by Swedz** [comment]
Is this something you can reliably reproduce? It shouldn't be possible for those values to be saved to the component.

**Comment by James103** [comment]
I was able to get a reliable reproduction in Craftoria 1.9.0:
1. Place down an assembler.
2. Place upgrades in the assembler's machine upgrade slot.
3. Use a Machine Config Card to copy the configuration from the assembler you placed in step 1.
4. Run `/data get entity @s SelectedItem` while holding the machine config card.
5. The command should work and write the data inside the card to chat.
6. Break the assembler.
7. While holding the same machine config card, run `/data get entity @s SelectedItem` again.
8. This time, the command fails with `An unexpected error occurred trying to execute that command`; the exact error according to the logs being: `Error saving [1 extended_industrialization:machine_config_card]. Original cause: java.lang.IllegalStateException: Value must be within range [1;99]: 0; Item must not be minecraft:air`
9. The Machine Config Card is now in an invalid state; you will need to shift-right-click the card to avoid crashes.

What probably happens is the data from the machine is copied to the card in such a way that breaking the original machine in Survival Mode causes the upgrade slots to be cleared to `0 air` in not just the machine (as its being destroyed) but the card's data.

**Comment by Swedz** [comment]
That makes a lot more sense, thank you. I can push a fix for this in a few minutes
