### ISSUE TITLE
Processing Array won't accept glass

### ISSUE THREAD

**Issue by MuteTiefling** [Swedz/Extended-Industrialization#9]
Mod Version: 1.4.2+1.21

![image](https://github.com/user-attachments/assets/aac4a070-cb20-42e6-ad8d-42dfa60fa26e)

**Comment by Swedz** [comment]
This is because the glass tag changed from `forge:glass` to `c:glass_blocks` in neoforge 1.21. I made the swap for everything to the common namespace, but I missed this one tag change. I'll have a fix for this in a few minutes once I get to my desk :p

**Comment by Swedz** [comment]
Fixed in 1.4.3

**Comment by MuteTiefling** [comment]
awesome, thanks!
