### ISSUE TITLE
(Enhancement) The Electric Brewery should be compatible with Modded Potion Recipes.

### ISSUE THREAD

**Issue by ArtpokeBr** [Swedz/Extended-Industrialization#90]
As Reported [here](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5735) It does not seem that the Electric Brewery is capable of Processing Modded Recipes, it would be nice to have this capability.

**Comment by Swedz** [comment]
In 1.20.4 the brewery worked differently than it does now. Back then, and now, it has support for modded potions. The report doesn't have much information, the brewery requires 4 potions to run. Are they providing 4 potions as input? Are they providing it with blaze powder?

**Comment by Swedz** [comment]
Just opened an instance on 1.20.4 neoforge and can confirm it doesn't work with the slow falling + fermented spider eye recipe from apothic attributes. However, this has already been fixed in newer versions of 1.21.1 and will not be backported.
